server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: medical-service
          uri: lb://medical-service
          predicates:
            - Path=/medical/**
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/patient/**
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/department/**
