server:
  port: 8100

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8104"
  cloud:
    gateway:
      routes:
        - id: medical_service
          uri: lb://medical_service
          predicates:
            - Path=/medical/**
        - id: patient_service
          uri: lb://patient_service
          predicates:
            - Path=/patient/**
        - id: department_service
          uri: lb://department_service
          predicates:
            - Path=/department/**
