server:
  port: 8103
  error:
    include-message: always

spring:
  config:
    import: "optional:configserver:http://localhost:8104"
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/Department
    username: root
    password: Clearme@1824
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: department_service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
logging:
  level:
    com.bruceycode.My_Rest_Api: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE